#!/bin/bash
# Date : (2012-12-16 21-06)
# Last revision : (2014-04-12 18-18)
# Wine version used : 1.4.1, 1.6.2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="mdk"
PREFIX="MDK_gog"
WORKING_WINE_VERSION="1.6.2"

TITLE="GOG.com - MDK"
SHORTCUT_NAME="MDK"

# left.jpg derivated from screenshot from hectichq.com
# top.jpg derivated from popsUlfr icon http://popsulfr.deviantart.com/art/MDK-Icon-118801430
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1514
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Shiny Entertainment / Interplay" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "a1e4dcdffd2de0d4f4dcbc3db30cbca6"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# fake sdbinst.exe
POL_Call POL_Install_nop "$WINEPREFIX/drive_c/windows/system32/sdbinst.exe" 

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

# "SVGA"
POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

# More "modern" default keyboard layout
# http://forums.steampowered.com/forums/showthread.php?t=973244
# scancodes <=> should be keymap independant
cat <<'_EOFCFG_' > "$WINEPREFIX/drive_c/GOG Games/MDK/MDK.CFG"
; MDK Configuration file automatically generated by MDK

cddata = 
hddata = 
hduse = 2
MouseWAxesMap = A0G
MouseWButtMapB = 2
MouseWButtMapC = 0
KeyUp = 44
KeyDown = 31
KeyJump = 57
KeyFire = 45
KeySniper = 56
KeyLookUp = 19
KeyLookDown = 33
KeyZoomIn = 19
KeyZoomOut = 33
KeySideL = 16
KeySideR = 32
ForcePCorrect = TRUE
D3DOptions = -1073610643
_EOFCFG_

POL_Shortcut "MDK3DFX.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/MDK/MANUAL.PDF"
# C:\GOG Games\MDK\readme.TXT

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/MDK/" || exit 1
TITLE="$TITLE"

POL_Wine nglide_config.exe
exit 0
_EOF_

exit 0

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iEYEABECAAYFAlNJd0oACgkQ5TH6yaoTykdKjACgiVDgcJYQ589Ks2aBb3X1fLjb
pusAnjTohN30gt36yOcK1dICXz+GgZu1
=QuqN
-----END PGP SIGNATURE-----
