POL_Call POL_Install_DXVK_192
cat << "-----END PGP SIGNATURE-----" > /dev/null
-----BEGIN PGP SIGNATURE-----

iF0EABECAB0WIQRFtWEU2eoWQNaBNczlMfrJqhPKRwUCYU8UfAAKCRDlMfrJqhPK
R27RAKCQMguFJK+LTxXJAxPDRVR86XgDagCggNZvZk6Q1eHLZBv4yM3J1xzumx0=
=YLrt
-----END PGP SIGNATURE-----
